### PR TITLE
clean up

### PR DESCRIPTION
**Pull request by VictorVictini**
- renamed GameState.cs to MoveState.cs
- cached the list used for bot guesses instead of creating a new one every time
- added a switch and removed a function for calculating what to output for each board point

### CODE REVIEW

**Comment by Deadly-Pigg** [comment]
toes. LGTM

**Comment by VictorVictini** [comment]
did you even read it 💀

**Comment by mohfez** [comment]
maybe make a function for checking who won instead of reusing the if statement

**Comment by VictorVictini** [comment]
good idea

**Comment by VictorVictini** [comment]
did it

**Pull request merged**
